### ISSUE TITLE
problem with human reactions

### ISSUE THREAD

**Issue by adugourd** [diegommcc/Generation-PKN-COSMOS#2]
Some reactions like ACO1 and MDH1 are annotated as TRANSPORTER and look wrong (like ACO1 transporting citrate from cytosole to cytosol) in the human PKN. After regenrating the PKN, the error was still there.

I checked in mouse and there it looks like the reactions are correctly created.

**Comment by diegommcc** [comment]
Bug already fixed. There was a mistake in the `.genes_to_symbol()` function, which is only called for the human PKN to translate genes from ENSEMBL to SYMBOL. Now, the number of TRANSPORTER + these examples are correct.
